# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.31"
cmkr-include = "cmkr.cmake"

[project]
name = "desktop-app-template"
description = "A simple template for cross-platform apps in C++"
languages = ["C", "CXX"]

[find-package.glfw3]
required = true

[find-package.imgui]
required = true

[vcpkg]
version = "2026.02.27"
packages = ["glfw3", "imgui[glfw-binding,opengl3-binding]"]

[variables]
CMAKE_EXPORT_COMPILE_COMMANDS = true

[target.template_app]
type = "executable" # static, shared
sources = [
    "src/**.cpp",

    # GLAD
    "external/glad/src/glad.c",
]
include-directories = [
    "external/glad/include",
    "src",
]
compile-features = ["cxx_std_23"]
link-libraries = ["glfw", "imgui::imgui"]
precompile-headers = ["src/pch.hpp"]
